[package]
name = "libint2"
version = "0.1.0"
authors = ["Eric Berquist <eric.berquist@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
cxx = "*"

[build-dependencies]
# bindgen = "*"
# cmake = "*"
cxx-build = "*"
